In [1]:
import pandas as pd
import numpy as np

## Feature Engineering

In [2]:
df = pd.read_csv(
    "cleaned_supplychain_data.csv"
)

df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [3]:
df["order_date"] = pd.to_datetime(
    df["order date (DateOrders)"]
)


df["shipping_date"] = pd.to_datetime(
    df["shipping date (DateOrders)"]
)


df["delivery_time"] = (
    df["shipping_date"] -
    df["order_date"]
).dt.days

In [4]:
df["profit"] = df["Benefit per order"]

In [5]:
df["inventory_demand"] = (
    df["Order Item Quantity"]
    *
    df["Sales"]
)

In [10]:
optimization_data = df[
[
"Delivery Status",
"Shipping Mode",
"delivery_time",
"profit",
"inventory_demand",
"Order Item Quantity"
]
]

optimization_data.head()

,Delivery Status,Shipping Mode,delivery_time,profit,inventory_demand,Order Item Quantity
0,Advance shipping,Standard Class,3,91.250000,327.75,1
1,Late delivery,Standard Class,5,-249.089996,327.75,1
2,Shipping on time,Standard Class,4,-247.779999,327.75,1
3,Advance shipping,Standard Class,3,22.860001,327.75,1
4,Advance shipping,Standard Class,2,134.210007,327.75,1

In [11]:
optimization_data.shape

(180519, 6)

In [13]:
optimization_data.to_csv(
"optimization_dataset.csv",
index=False
)